### ISSUE TITLE
Add screenshot that shows upscaling

### ISSUE THREAD

**Issue by ssokolow** [flathub/com.github.opentyrian.OpenTyrian#1]
The current screenshot makes OpenTyrian look like one of those Windows 9x-era games that has a tiny window unless it can change the monitor resolution and not everyone is familiar with that era.

It'd be a good idea to either replace that screenshot or add another one with upscaling enabled to demonstrate that you don't *have* to play it with the game window so tiny compared to the titlebar.

**Comment by Laserlicht** [comment]
@ssokolow I've updated the screenshots. If you have one with hq4x you can add it for example to [ModDB](https://www.moddb.com/games/opentyrian). After that I can link it here.
